---
- name: Build boxfuse
  hosts: build
  become: yes

  tasks:
  - name: Ensure git pkg is present
    apt:
      name: git
      state: present

  - name: Ensure maven pkg is present
    apt:
      name: maven
      state: present

  - name: Clone boxfuse repo
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /src/boxfuse-sample-java-war-hello

  - name: Build boxfuse using maven
    shell:
      chdir: /src/boxfuse-sample-java-war-hello/
      executable: /bin/bash
      cmd: mvn package

